title: Origin-Destination Visualization using STPLANR
logo: /assets/img/pa_ct_centroid.png
description: Exploring O-D demographics for Philadelphia.
show_downloads: false
repository: MUSA-550-Fall-2021/github-pages-single-page-starter
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
